<html><body><h2>File (last 1,000 lines): /var/log/apx-bundler/apx-bundler.log</h2><table><tr><td bgcolor=#CCCCCC><b>Critical(s):</b></td><td bgcolor=#FF0000><b>0</b></td></tr><tr><td bgcolor=#CCCCCC><b>Error(s):</b></td><td bgcolor=#FF0000><b>11</b></td></tr><tr><td bgcolor=#CCCCCC><b>Fatal(s):</b></td><td bgcolor=#FF0000><b>30</b></td></tr><tr><td bgcolor=#CCCCCC><b>Serialize(s):</b></td><td bgcolor=#FFFF00><b>0</b></td></tr><tr><td bgcolor=#CCCCCC><b>Warning(s):</b></td><td bgcolor=#FFFF00><b>0</b></td></tr></table><br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:10:16,268 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:10:16,284 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:10:16,322 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:10:16,363 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:10:16,378 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>13 Aug 2014 00:10:16,381 INFO  [Thread-30]: {message=Inserted 0 events.}<br>13 Aug 2014 00:10:16,455 EVENT [Thread-30]: {jvm.processors.count=4, bundler.consume.org_id=306, datestamp=2014-08-13T00:10:15.917Z, bundler.consume.channel=Stagingchannel_scienceproject, jvm.memory.total.count=1, jvm.threads.count=65, bundler.consume.count=1, bundler.consume.message=09151455-9964-4257-89b8-744149aa9003___306, jvm.memory.free.bytes=1138352304, bundler.consume.raw_events=0, bundler.consume.generated_opportunities=0, jvm.memory.max.bytes=3728211968, jvm.thread=58, bundler.consume.millis=538, bundler.consume.status=success, hostname=ip-10-198-28-247, jvm.memory.total.bytes=3167748096, bundler.consume.event_batch_id=09151455-9964-4257-89b8-744149aa9003, jvm.memory.max.count=1, time=1407888615917, jvm.memory.free.count=1}<br>13 Aug 2014 00:10:16,455 INFO  [Thread-30]: {message=Ending: bundler.consume}<br>13 Aug 2014 00:14:25,621 INFO  [Thread-30]: Message c2d7baef-4d7d-4fe1-94dc-e8e371fe44ae___306 received on Channel Stagingchannel_scienceproject<br>13 Aug 2014 00:14:25,621 INFO  [Thread-30]: {message=Starting: bundler.consume}<br>13 Aug 2014 00:14:25,622 INFO  [Thread-30]: {message=Checking org id = 306}<br>13 Aug 2014 00:14:25,622 INFO  [Thread-30]: {message=Org id 306 exists... we're good.}<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 00:14:25,653 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>13 Aug 2014 00:14:25,656 INFO  [Thread-30]: {message=Inserted 0 events.}<br>13 Aug 2014 00:14:25,732 EVENT [Thread-30]: {jvm.processors.count=4, bundler.consume.org_id=306, datestamp=2014-08-13T00:14:25.621Z, bundler.consume.channel=Stagingchannel_scienceproject, jvm.memory.total.count=1, jvm.threads.count=65, bundler.consume.count=1, bundler.consume.message=c2d7baef-4d7d-4fe1-94dc-e8e371fe44ae___306, jvm.memory.free.bytes=1088828208, bundler.consume.raw_events=0, bundler.consume.generated_opportunities=0, jvm.memory.max.bytes=3728211968, jvm.thread=58, bundler.consume.millis=111, bundler.consume.status=success, hostname=ip-10-198-28-247, jvm.memory.total.bytes=3167748096, bundler.consume.event_batch_id=c2d7baef-4d7d-4fe1-94dc-e8e371fe44ae, jvm.memory.max.count=1, time=1407888865621, jvm.memory.free.count=1}<br>13 Aug 2014 00:14:25,733 INFO  [Thread-30]: {message=Ending: bundler.consume}<br>13 Aug 2014 02:28:58,122 INFO  [Thread-30]: Message 95a01f4e-5e4b-483d-acd7-0c4f9429eb67___299 received on Channel Stagingchannel_scienceproject<br>13 Aug 2014 02:28:58,123 INFO  [Thread-30]: {message=Starting: bundler.consume}<br>13 Aug 2014 02:28:58,123 INFO  [Thread-30]: {message=Checking org id = 299}<br>13 Aug 2014 02:28:58,123 INFO  [Thread-30]: {message=Org id 299 exists... we're good.}<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 02:28:58,178 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 02:28:58,196 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>13 Aug 2014 02:28:58,199 INFO  [Thread-30]: {message=Inserted 0 events.}<br>13 Aug 2014 02:28:58,276 EVENT [Thread-30]: {jvm.processors.count=4, bundler.consume.org_id=299, datestamp=2014-08-13T02:28:58.123Z, bundler.consume.channel=Stagingchannel_scienceproject, jvm.memory.total.count=1, jvm.threads.count=65, bundler.consume.count=1, bundler.consume.message=95a01f4e-5e4b-483d-acd7-0c4f9429eb67___299, jvm.memory.free.bytes=801990336, bundler.consume.raw_events=0, bundler.consume.generated_opportunities=0, jvm.memory.max.bytes=3728211968, jvm.thread=58, bundler.consume.millis=153, bundler.consume.status=success, hostname=ip-10-198-28-247, jvm.memory.total.bytes=3167748096, bundler.consume.event_batch_id=95a01f4e-5e4b-483d-acd7-0c4f9429eb67, jvm.memory.max.count=1, time=1407896938123, jvm.memory.free.count=1}<br>13 Aug 2014 02:28:58,276 INFO  [Thread-30]: {message=Ending: bundler.consume}<br>13 Aug 2014 02:29:19,342 INFO  [Thread-30]: Message b3daf9ad-a53f-425f-b74a-102bd9f3658e___299 received on Channel Stagingchannel_scienceproject<br>13 Aug 2014 02:29:19,343 INFO  [Thread-30]: {message=Starting: bundler.consume}<br>13 Aug 2014 02:29:19,343 INFO  [Thread-30]: {message=Checking org id = 299}<br>13 Aug 2014 02:29:19,343 INFO  [Thread-30]: {message=Org id 299 exists... we're good.}<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 02:29:19,373 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 1<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 1<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 2<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 2<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>Connection using primary DNS, https://prodks.apixio.com/keyservice/getkey.do failed , count = 3<br>Exception is : sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>Connection using secondary DNS, null failed , count = 3<br>Exception is : no protocol: null?token=eg7%26qoivth34551555TYLLIHT%24%25123RES<br>javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.ssl.Alerts.getSSLException(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.fatal(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.Handshaker.fatalSE(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.serverCertificate(Unknown Source)<br>	at sun.security.ssl.ClientHandshaker.processMessage(Unknown Source)<br>	at sun.security.ssl.Handshaker.processLoop(Unknown Source)<br>	at sun.security.ssl.Handshaker.process_record(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.readRecord(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsClient.afterConnect(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.setNewClient(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.writeRequests(Unknown Source)<br>	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)<br>	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)<br>	at com.apixio.security.KeyReceiver.getKeyFromService(KeyReceiver.java:21)<br>	at com.apixio.security.ApixioKey2.getKeyFromService(ApixioKey2.java:23)<br>	at com.apixio.security.ApixioKey2.getKey(ApixioKey2.java:18)<br>	at com.apixio.security.Security.getDecryptKey(Security.java:181)<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:454)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.validator.PKIXValidator.doBuild(Unknown Source)<br>	at sun.security.validator.PKIXValidator.engineValidate(Unknown Source)<br>	at sun.security.validator.Validator.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)<br>	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)<br>	... 41 more<br>Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target<br>	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)<br>	at java.security.cert.CertPathBuilder.build(Unknown Source)<br>	... 47 more<br>An exception occurred !!<br>13 Aug 2014 02:29:19,389 ERROR [Thread-30]: Could not decrypt the event list data sent.<br>com.apixio.security.exception.ApixioSecurityException<br>	at com.apixio.security.Security.decryptBytesToBytes(Security.java:466)<br>	at com.apixio.dao.event.eventdao.EventDataUtility.getEvents(EventDataUtility.java:47)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:346)<br>	at com.apixio.dao.event.eventdao.EventDAO$BatchEventIterator.next(EventDAO.java:321)<br>	at scala.collection.convert.Wrappers$JIteratorWrapper.next(Wrappers.scala:42)<br>	at scala.collection.Iterator$$anon$13.hasNext(Iterator.scala:371)<br>	at scala.collection.Iterator$class.foreach(Iterator.scala:727)<br>	at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)<br>	at scala.collection.TraversableOnce$class.size(TraversableOnce.scala:105)<br>	at scala.collection.AbstractIterator.size(Iterator.scala:1157)<br>	at scala.collection.Iterator$class.length(Iterator.scala:1029)<br>	at scala.collection.AbstractIterator.length(Iterator.scala:1157)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:171)<br>	at com.apixio.hcc.bundler.service.EventConsumer$$anonfun$consumeMessage$1.apply(EventConsumer.scala:140)<br>	at scala.util.Try$.apply(Try.scala:161)<br>	at com.apixio.util.logging.Loggable$class.withLogging(Loggable.scala:255)<br>	at com.apixio.hcc.bundler.service.EventConsumer.withLogging(EventConsumer.scala:29)<br>	at com.apixio.hcc.bundler.service.EventConsumer.consumeMessage(EventConsumer.scala:190)<br>	at com.apixio.datasource.redis.ChannelHandle.onMessage(ChannelHandle.java:31)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:134)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>13 Aug 2014 02:29:19,391 INFO  [Thread-30]: {message=Inserted 0 events.}<br>13 Aug 2014 02:29:19,463 EVENT [Thread-30]: {jvm.processors.count=4, bundler.consume.org_id=299, datestamp=2014-08-13T02:29:19.343Z, bundler.consume.channel=Stagingchannel_scienceproject, jvm.memory.total.count=1, jvm.threads.count=65, bundler.consume.count=1, bundler.consume.message=b3daf9ad-a53f-425f-b74a-102bd9f3658e___299, jvm.memory.free.bytes=780816144, bundler.consume.raw_events=0, bundler.consume.generated_opportunities=0, jvm.memory.max.bytes=3728211968, jvm.thread=58, bundler.consume.millis=120, bundler.consume.status=success, hostname=ip-10-198-28-247, jvm.memory.total.bytes=3167748096, bundler.consume.event_batch_id=b3daf9ad-a53f-425f-b74a-102bd9f3658e, jvm.memory.max.count=1, time=1407896959343, jvm.memory.free.count=1}<br>13 Aug 2014 02:29:19,463 INFO  [Thread-30]: {message=Ending: bundler.consume}<br>13 Aug 2014 14:40:34,343 ERROR [Thread-30]: Subscribing failed.<br>redis.clients.jedis.exceptions.JedisConnectionException: java.net.SocketException: Connection timed out<br>	at redis.clients.jedis.Protocol.process(Protocol.java:131)<br>	at redis.clients.jedis.Protocol.read(Protocol.java:187)<br>	at redis.clients.jedis.Connection.getRawObjectMultiBulkReply(Connection.java:221)<br>	at redis.clients.jedis.JedisPubSub.process(JedisPubSub.java:109)<br>	at redis.clients.jedis.JedisPubSub.proceed(JedisPubSub.java:103)<br>	at redis.clients.jedis.Jedis.subscribe(Jedis.java:2753)<br>	at com.apixio.datasource.redis.PubSub$1.run(PubSub.java:149)<br>Caused by: java.net.SocketException: Connection timed out<br>	at java.net.SocketInputStream.socketRead0(Native Method)<br>	at java.net.SocketInputStream.read(Unknown Source)<br>	at java.net.SocketInputStream.read(Unknown Source)<br>	at java.net.SocketInputStream.read(Unknown Source)<br>	at redis.clients.util.RedisInputStream.fill(RedisInputStream.java:109)<br>	at redis.clients.util.RedisInputStream.readByte(RedisInputStream.java:45)<br>	at redis.clients.jedis.Protocol.process(Protocol.java:116)<br>	... 6 more<br></body></html>